### ISSUE TITLE
Can you patch it to use anywhere, even in other OS

### ISSUE THREAD

**Issue by lotusdroid** [Leaked0/Ghost-Toolbox#1]
Thank you

**Comment by HideakiAtsuyo** [comment]
> Thank you

Why would I want to do that ? Anyone that know a bit of batch can do it.. 😐

**Comment by HideakiAtsuyo** [comment]
+ Ghost Specter is not a fully-fledged operating system it's just a "modded" windows so it would only work on Windows

**Comment by lotusdroid** [comment]
🥲I know a little bit but required file is missing

**Comment by HideakiAtsuyo** [comment]
> 🥲I know a little bit but required file is missing

Required file is missing ? Which file ?

**Comment by lotusdroid** [comment]
Some dll files, winget,..
I patched it to remove all warning but it crashed

**Comment by HideakiAtsuyo** [comment]
> Some dll files, winget,.. I patched it to remove all warning but it crashed

Yeah I see at 25 stars I I'll upload all required files, specifie where they need to be, remove the restriction to let anyone use it on any Windows version etc..

**Comment by lotusdroid** [comment]
Thank u very much guy🥰
I will wait for it
